### ISSUE TITLE
Mapping between the red-teaming data and safety data

### ISSUE THREAD

**Issue by ys-zong** [vinid/instruction-llms-safety-eval#1]
Hi, thanks for sharing the code! You mentioned in the paper they are rephased from Anthropic Red Teaming data to instructions. I'm wondering if would it be possible for you to share the corresponding mappings, i.e. which instruction data corresponds to which original red-teaming data. Many thanks!

**Comment by vinid** [comment]
Thanks so much for reaching out! Here's the data you are looking for! it has the original question, the answer, and the translated instruction!

[export_redteam_anth_instruction.csv](https://github.com/vinid/instruction-llms-safety-eval/files/13777294/export_redteam_anth_instruction.csv)

**Comment by ys-zong** [comment]
Thank you very much!
