### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by FYYFU** [vinid/instruction-llms-safety-eval#2]
Hi! Thanks for you awesome code!! How can we download the safety-tuned Llama2 (or Falcon) model? 
And If there exist some problems, could you please give some training scripts to reproduce the safety fine-tuned model?

Thanks for your reply. 😆

**Comment by vinid** [comment]
Hello!

Here is the [Finetuning Code](https://github.com/vinid/instruction-llms-safety-eval/blob/main/training/finetuninig.py). Note that this is based on [Alpaca-lora](https://github.com/tloen/alpaca-lora/) code.

We have the models on HuggingFace, but we need to do a bit of cleanup before releasing them; they will probably be ready for the camera-ready version of the paper.

**Comment by FYYFU** [comment]
> Hello!
> 
> Here is the [Finetuning Code](https://github.com/vinid/instruction-llms-safety-eval/blob/main/training/finetuninig.py). Note that this is based on [Alpaca-lora](https://github.com/tloen/alpaca-lora/) code.
> 
> We have the models on HuggingFace, but we need to do a bit of cleanup before releasing them; they will probably be ready for the camera-ready version of the paper.

Perfect! I'll sure to try it.

**Comment by FYYFU** [comment]
> Hello!
> 
> Here is the [Finetuning Code](https://github.com/vinid/instruction-llms-safety-eval/blob/main/training/finetuninig.py). Note that this is based on [Alpaca-lora](https://github.com/tloen/alpaca-lora/) code.
> 
> We have the models on HuggingFace, but we need to do a bit of cleanup before releasing them; they will probably be ready for the camera-ready version of the paper.

And a big congratulations on the acceptance of your awesome paper! Hope to see your released models.

**Comment by vinid** [comment]
Tysm!!
