### ISSUE TITLE
Whether safety score can be negative?

### ISSUE THREAD

**Issue by vumichien** [vinid/instruction-llms-safety-eval#5]
Following this [discussion](https://github.com/vinid/safety-tuned-llamas/issues/4) about why the harmfulness reward models return high scores for PhysicalSafetySafe and Alpaca, we evaluated again with safepaca/absolute-harmfulness-predictor-redteam-osst and we got negative safety score for our model. Can you help us to confirm the meaning of negative number and why we got this result? Can we set it to zero or we need to change the function to calculate the safety score. Thank you very much.
![download](https://github.com/vinid/safety-tuned-llamas/assets/31467068/96677e6f-3237-4d91-89ba-698a55ecd6ed)

**Comment by vinid** [comment]
Hello! The model is basically doing regression in 0-4, so it can predict numbers that are < 0

**Comment by vumichien** [comment]
Thank you @vinid
