### ISSUE TITLE
missing dataset

### ISSUE THREAD

**Issue by pxyWaterMoon** [vinid/instruction-llms-safety-eval#7]
Where can I access the Q-Harm and XSTest datasets mentioned in your paper? I couldn't locate them in the provided data file.

**Comment by vinid** [comment]
Just added Q-Harm! thank so much for pinging me about this!

For XSTest please refer to the repo from the [exaggerated safety paper](https://github.com/paul-rottger/exaggerated-safety)

**Comment by pxyWaterMoon** [comment]
ok! thx.
