### ISSUE TITLE
Evaluation on BoolQ, PIQA and OpenBookQA

### ISSUE THREAD

**Issue by luyuxiao** [vinid/instruction-llms-safety-eval#8]
Could you please release the evaluation code on BoolQ, PIQA and OpenBookQA? I run the code using llama-7b and the harfulness score is aligned with the results reported in the paper but the correct rate on BoolQ is just slightly higher than 50% (much lower than 77% reported in the paper)

**Comment by vinid** [comment]
Hello! 

we used https://github.com/EleutherAI/lm-evaluation-harness to compute those scores!

**Comment by luyuxiao** [comment]
Thank you! It works 👍
